<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.108" timestamp="2025-08-17T19:09:17.679269+01:00" hostname="delonix"><testcase classname="tests.test_load" name="test_load_positive_has_2_people" time="0.001"><failure message="AssertionError: assert 3 == 2&#10; +  where 3 = len(['Jim Halpert, Sales, Salesman, jim@dundlermifflin.com', 'Dwight Schrute, Sales, Manager, schrute@dundlermifflin.com', 'El Dougle, Sales, Representative, el@dundlermifflin.com'])">@pytest.mark.unit
    @pytest.mark.high
    def test_load_positive_has_2_people():
        """Test the load function."""
        # side effect: create the file if it does not exist
    
        data = load(PEOPLE_FILE)
&gt;       assert len(data) == 2
E       AssertionError: assert 3 == 2
E        +  where 3 = len(['Jim Halpert, Sales, Salesman, jim@dundlermifflin.com', 'Dwight Schrute, Sales, Manager, schrute@dundlermifflin.com', 'El Dougle, Sales, Representative, el@dundlermifflin.com'])

tests/test_load.py:14: AssertionError</failure></testcase><testcase classname="tests.test_load" name="test_load_positive_first_name_starts_with_j" time="0.000" /><testcase classname="integration.test_load" name="test_load" time="0.051" /></testsuite></testsuites>